name: 3D Contributions
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Graph
        uses: yoshi38911/github-profile-3d-contrib@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Commit and Push 3D Graph
        uses: stefanwa/git-auto-commit-action@v5
        with:
          commit_message: Update 3D contribution graph
          file_pattern: profile-3d-contrib/profile-night-rainbow.svg
  
