name: 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3d-graph
          path: ./profile-3d-contrib
