name: Contribution Heatmap Animation
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Heatmap
        uses: Ashutosh00710/github-readme-contrib-stats@v1.2 # Using v1.2 as intended
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and Push Heatmap
  
        uses: stefanwa/git-auto-commit-action@master 
        with:
          commit_message: Update contribution heatmap SVG
          file_pattern: contributions.svg
